name: Build and Deploy Node.js with PM2

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: sudo npm install

      - name: Build app
        run: npm run build

      - name: Install PM2 globally
        run: sudo npm install -g pm2

      - name: Restart app with PM2
        run: |
          cd /home/ubuntu/buildanddeploy/dist
          pm2 delete all || true
          pm2 start index.js
          pm2 save
